### ISSUE TITLE
Rain and Snow is always NULL mm

### ISSUE THREAD

**Issue by FChristian** [ioBroker/ioBroker.openweathermap#1]
Great adapter idea and work, THANK YOU VERY MUCH FOR THIS!!!

One issue I#ve found: the objects in iobroker for rain (and snow?) always shows NULL or 0 mm, even if the website (and the API data) transmits a value for this.

**Comment by libertyx82** [comment]
Das liegt wohl daran, dass in der API die Werte
bei "current" als

```
rain
rain.1h Rain volume for the last 1 hour
rain.3h Rain volume for the last 3 hours
snow
snow.1h Snow volume for the last 1 hour
snow.3h Snow volume for the last 3 hours
```
und in der 5 Tage / 3 Stunden Vorhersage als

```
list.rain
list.rain.3h Rain volume for last 3 hours, mm
list.snow
list.snow.3h Snow volume for last 3 hours
```

**Comment by libertyx82** [comment]
With the changes i have made in Pull request https://github.com/ioBroker/ioBroker.openweathermap/pull/7 it is fixed

**Comment by jardleex** [comment]
Hey there,
for me the issue is still present. I've installed the adapter per iobroker default and also did an update via GitHub URL but rain/snow only shows NULL or 0 mm.
Any ideas?

**Comment by vowchr** [comment]
Same for me - I always get NULL or 0mm, even for a rainy day... :-(

**Comment by libertyx82** [comment]
Also mit der Version von hier funktioniert das einwandfrei, die Werte werden allerdings von openweather nur unzuverlässig gemeldet, daran kann der Adapter nichts ändern.

**Comment by jardleex** [comment]
FYI: I'm keeping this in English so the world can follow too.

Had to wait for a rainy day which is the case here today (city id 2879139).
I've checked the json coming from `http://api.openweathermap.org/data/2.5/forecast?id=2879139&APPID=..` and found valid values like
```
...
      "rain": {
        "3h": 3.063
      },
...
```
Which do not seem to be reflected correct in the adapter.

How can I verify the exact version / commit hash I'm using for this adapter in iobroker?
The adapters view tells me 0.1.0, even after a GitHub update.

I'm running iobroker in Docker > athalis/iobroker.
This is the output after a GitHub update of the adapter:
```
$ ./iobroker url "https://github.com/ioBroker/ioBroker.openweathermap/tarball/master" openweathermap --debug
install https://github.com/ioBroker/ioBroker.openweathermap/tarball/master
npm install https://github.com/ioBroker/ioBroker.openweathermap/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.discovery/package.json'npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.radar/package.json'


+ iobroker.openweathermap@0.1.0updated 1 package and audited 520 packages in 10.391s

found 1 low severity vulnerability  run `npm audit fix` to fix them, or `npm audit` for details

got /opt/iobroker/node_modules/iobroker.openweathermap/admin
upload [3] openweathermap.admin /opt/iobroker/node_modules/iobroker.openweathermap/admin/words.js words.js application/javascript
upload [2] openweathermap.admin /opt/iobroker/node_modules/iobroker.openweathermap/admin/openweathermap.png openweathermap.png image/png
upload [1] openweathermap.admin /opt/iobroker/node_modules/iobroker.openweathermap/admin/index_m.html index_m.html text/html
upload [0] openweathermap.admin /opt/iobroker/node_modules/iobroker.openweathermap/admin/index.html index.html text/html
process exited with code 0
```

**Comment by libertyx82** [comment]
> FYI: I'm keeping this in English so the world can follow too.
> 
> Had to wait for a rainy day which is the case here today (city id 2879139).
> I've checked the json coming from `http://api.openweathermap.org/data/2.5/forecast?id=2879139&APPID=..` and found valid values like
> 
> ```
> ...
>       "rain": {
>         "3h": 3.063
>       },
> ...
> ```
> 
> Which do not seem to be reflected correct in the adapter.

1h are metered Data from connected Stations
3h are model data (forecast)

For current only the 1h Value is relevant

**Comment by jardleex** [comment]
Okay, checked `http://api.openweathermap.org/data/2.5/weather?id=2879139&APPID=`
and got 

```
...
  "rain": {
    "1h": 1.02
   },
...
```
but in iobroker still `null mm` is shown.

Can you say something about the update code block I posted? Maybe the update to the latest master failed and I still use version **0.1.0.**

**Comment by libertyx82** [comment]
Today it is raining an i can check and it works corectly

![image](https://user-images.githubusercontent.com/22996350/58102265-4d860e80-7be1-11e9-9385-22a6455fd053.png)

What you can try is to install the adapter from the repro and after that you replace the io-package.json with the one from here.

**Comment by jardleex** [comment]
Things learned so far.
- Installing this adapter via GitHub tab in iobroker instances does not fully work. It appears in the adapters list, but not as an configurable instance.
- Same for installation from custom URL (tested with URL to this GIT repo).
- Installing the adapter per default way via installation by klick from the available adapters list works
- Updating the adapter then via GitHub URL works too.

I've verified to have the same md5sum of `io-packages.json` under `/opt/iobroker/node_modules/iobroker.openweathermap/` as in the current master  (86b62ed1beb39aba3b4a0f03eb9dc027).

As I've just reinstalled the adapter and it's not raining, it seems I have to wait some days.

Note: I'm using coordinates for the location setting in the adapter, not a pre-defined location.

**Comment by jardleex** [comment]
I continued digging on the json delivered by openweathermap and the data shown by the adapter.
I have a glimpse why some days have **NULL** for rain. 
Based on the output of `curl -s 'http://api.openweathermap.org/data/2.5/forecast?id=2879139&APPID=...' | jq '.list[] | {date_time: .dt_txt, rain: .rain}'`
**Options**
- A: If the LAST rain object of a day is null the adapter _breaks_ and lists NULL in the GUI
- B: If a CERTAIN timeframe of the 3h object is null the adapter _breaks_ and lists NULL in the GUI. The adapter always show 2 pm as time for forecast of the next days (date field in objects list). As openweathermap only provides 1pm and 3pm data, I can only guess which of the slots causes the display issue of NULL



I expect a **0** as a valid number as the adapter seem to round the values provided by openwathermap. E.g. 0.125 would be 0 mm.

**Comment by libertyx82** [comment]
Der Adpater ruft immer beide API´s ab

Für die Daten unter "day0, day1, day2. day3, day4, day5"
https://api.openweathermap.org/data/2.5/forecast?

und für die Daten unter "current"
https://api.openweathermap.org/data/2.5/weather?

Die API liefert nicht immer alle Datenpunkte sondern nur die, für die auch Daten verfügbar sind, heißt gibt es für z.B. Rain keine Daten, dann fehlt der Datenpunkt und der Adapter zeigt "NULL"

Der Datenpunkt "Rain" liefert auch nur Durchschnittswerte für die letzte Stunde (1h) und die letzten drei Stunden (3h) hier nur als forecast. Regnet es länger als eine Stunde nicht, wechselt der Datenpunkt erst auf 0 und dann auf NULL weil keine Daten mehr geliefert werden, einen Tageswert wird nicht geliefert.

Der 3h Wert (forecast) für den aktuellen Tag wird unter "day0" angezeigt statt unter "current" da es ein Forecast ist.

Da die forecast API Daten im 3 Stunden Zyklus meldet, werden die Daten für einen Tag summiert und unter dem entsprechenden Tag "day1" usw. angezeigt.

Eine Rundung findet nicht statt, weder bei "current" noch bei "forecast"

Als Tipp, wenn du verlässliche Regendaten und auch einen Tageswert haben möchtest solltest du den neuen Adapter für weatherunderground benutzen.
https://github.com/iobroker-community-adapters/ioBroker.weatherunderground

**Comment by Apollon77** [comment]
For completion: 
> Installing this adapter via GitHub tab in iobroker instances does not fully work. It appears in the adapters list, but not as an configurable instance.
This is intended behaviour for GitHub/URL installs. All standard cases to install from a repository work as expected

> Updating the adapter then via GitHub URL works too.
Correct, but for Github install the adapter instances are not restarted after the update! This is also intended!

**Comment by jardleex** [comment]
@libertyx82 
Thanks for clearification. That sheds some light on how the adapter behaves.
For me I'd say this can get closed as everything works as you described it.

@Apollon77 
Thanks for your input too. This will help me on futher work with iobroker.

**Comment by shizophren83** [comment]
Don't know if this project is still alive, but I have still the same issue. Rain is always null mm.
Was this somehow fixed in the meantime?

**Comment by libertyx82** [comment]
@shizophren83 

Do you have read my clarification here?
https://github.com/ioBroker/ioBroker.openweathermap/issues/1#issuecomment-494517476

It is not an Issue if the Adapter shows "NULL" on Data points

**Comment by shizophren83** [comment]
> @shizophren83
> 
> Do you have read my clarification here?
> [#1 (comment)](https://github.com/ioBroker/ioBroker.openweathermap/issues/1#issuecomment-494517476)
> 
> It is not an Issue if the Adapter shows "NULL" on Data points

Thanks mate. Missed that. Will try your tipp with the other adapter.
