### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.openweathermap#11]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/ioBroker/ioBroker.openweathermap

- [x] [E300] Not found on travis. Please setup travis
- [x] [E802] No topics found in the repository. Please go to "https://github.com/ioBroker/ioBroker.openweathermap", press the settings button beside the about title and add some topics.

I have also found warnings that may be fixed if possible.

- [x] [W505] setTimeout found in "main.js", but no clearTimeout detected

Thanks,
your automatic adapter checker.

**Comment by libertyx82** [comment]
https://github.com/ioBroker/ioBroker.openweathermap/pull/17

https://github.com/ioBroker/ioBroker.openweathermap/pull/16

https://github.com/ioBroker/ioBroker.openweathermap/pull/15

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?
