### ISSUE TITLE
openweathermap.0.forecast.day1.date (today +1) does not display the correct date in vis

### ISSUE THREAD

**Issue by ioc73** [ioBroker/ioBroker.openweathermap#12]
If you select the openweathermap.0.forecast.day1.date in a vis view, the value does not show the correct date (today +1).
in the object it self the value shows the correct date for day1.

I this a knowen issue or am I doing anything wrong?

Bye

**Comment by Apollon77** [comment]
Is the value only not shown correctly in the "ID selection window" or also not correctly in vis?
If first one: which js-controller and which Admin and which vis version?

**Comment by ioc73** [comment]
Hello Apollon77,
the objects in iobroker it self seems to be ok. See attachment one.
But in vis, in the selection is a number shown. See attachment two. 
I have checked this number in excel as I thought i could be the wrong format. But even there there is no way of formating it to a date.
![1_correct_in_objects](https://user-images.githubusercontent.com/26593766/54842674-d0b6e100-4cd2-11e9-94bb-357aaf4dc302.JPG)
![2_view_in_vis](https://user-images.githubusercontent.com/26593766/54842683-d7ddef00-4cd2-11e9-8099-1ffbeaa312ff.JPG)

Bye

**Comment by ioc73** [comment]
Hello,
know has an idea?
Bye

**Comment by Apollon77** [comment]
Ok, if it is just that the vis selection shows the timestamp as number while admin shows it as date then please open Admin issue to fix the "ID selector" for adapters
