### ISSUE TITLE
Change Weather API "5-day" with "16-day"

### ISSUE THREAD

**Issue by Haba1234** [ioBroker/ioBroker.openweathermap#13]
Hello!
I suggest replacing the Weather API "5-day / 3-hour forecast" with "16-day / daily forecast." "TemperatureMax", "TemperatureMin", "Prediction Status" and other values for the selected day will be displayed correctly.

**Comment by libertyx82** [comment]
The 16 Day Forecast is only available with an paid "starter" subscription (40$ / Month)
https://openweathermap.org/price
