### ISSUE TITLE
no more weather dates since May 30th noon?

### ISSUE THREAD

**Issue by virgin09** [ioBroker/ioBroker.openweathermap#26]
when I start the adapter since the date specified I keep receiving the following error messages:

`

openweathermap.0 | 2020-05-31 12:19:01.302 | error | (25666) TypeError: Cannot read property 'statusCode' of undefined at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.openweathermap/main.js:255:47) at self.callback (/opt/i
-- | -- | -- | --
openweathermap.0 | 2020-05-31 12:19:01.302 | error | (25666) uncaught exception: Cannot read property 'statusCode' of undefined

In Ergänzung weitere Fehlermeldungen:

`

host.debian-VB | 2020-05-31 12:23:04.249 | info | instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
openweathermap.0 | 2020-05-31 12:23:03.744 | info | (25685) Terminated (NO_ERROR): Without reason
openweathermap.0 | 2020-05-31 12:23:03.744 | info | (25685) terminating
openweathermap.0 | 2020-05-31 12:23:03.241 | error | (25685) TypeError: Cannot read property 'statusCode' of undefined at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.openweathermap/main.js:255:47) at self.callback (/opt/i
openweathermap.0 | 2020-05-31 12:23:03.240 | error | (25685) uncaught exception: Cannot read property 'statusCode' of undefined
openweathermap.0 | 2020-05-31 12:23:03.026 | info | (25685) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v8.16.0
host.debian-VB | 2020-05-31 12:23:00.025 | info | instance system.adapter.openweathermap.0 started with pid 25685
host.debian-VB | 2020-05-31 12:19:02.321 | info | instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)
openweathermap.0 | 2020-05-31 12:19:01.806 | info | (25666) Terminated (NO_ERROR): Without reason
openweathermap.0 | 2020-05-31 12:19:01.806 | info | (25666) terminating
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at TLSSocket.emit (events.js:211:7)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at emitOne (events.js:116:13)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at ClientRequest.emit (events.js:211:7)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at emitOne (events.js:116:13)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at Request.onRequestError (/opt/iobroker/node_modules/iobroker.openweathermap/node_modules/request/request.js:881:8)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at Request.emit (events.js:211:7)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at emitOne (events.js:116:13)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at self.callback (/opt/iobroker/node_modules/iobroker.openweathermap/node_modules/request/request.js:185:22)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.openweathermap/main.js:255:47)
openweathermap.0 | 2020-05-31 12:19:01.302 | error | (25666) TypeError: Cannot read property 'statusCode' of undefined
openweathermap.0 | 2020-05-31 12:19:01.302 | error | (25666) uncaught exception: Cannot read property 'statusCode' of undefined
openweathermap.0 | 2020-05-31 12:19:01.051 | info | (25666) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v8.16.0

`
`

**Comment by Apollon77** [comment]
Issue still existing? I do not think so
