### ISSUE TITLE
Keine Niederschlagsvorhersage

### ISSUE THREAD

**Issue by ing-michel** [ioBroker/ioBroker.openweathermap#30]
Moin,
vielen Dank @libertyx82 für Dein Plugin.

Leider werden keine Niederschlagsvorhersagen angezeigt. Die Vorhersage ist immer "0" mm.
Beste Grüße  Michel

**Comment by jensb** [comment]
I have the same problem: no rain forecast and info, always 0 or "null".
How do we fix this?

**Comment by jensb** [comment]
This seems to be a little more complicated. The "rain" key is only returned in JSON when there is actually rain. So the response during rain is something like:

![image](https://user-images.githubusercontent.com/44540/123690255-75321100-d854-11eb-9fb9-dadc88302228.png)

Now just somebody needs to implement this in the code ... :-)

**Comment by Apollon77** [comment]
duplicate #1
