### ISSUE TITLE
Feature request: Support One Call API 3.0

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.openweathermap#380]
The One Call API 3.0, which can be used for free if you use max 1000 requests/day, offers additional data like minutely forcast.
Would be great if someome who subscribes to the One Call API 3.0 would get this data.
e.g. Switch in Instanz "Use One Call API 3.0  yes/no"

Details about data structure etc. could be found in the api docu incl. JSON expample.
[https://openweathermap.org/api/one-call-3](https://openweathermap.org/api/one-call-3)

**Comment by Horgul123** [comment]
Seems to be related to other requests, sorry.

**Comment by Apollon77** [comment]
Is that really done?

**Comment by Horgul123** [comment]
@Apollon77 no. But 2 similar issues are still open. So a third one doesn't make sense, does it?
