### ISSUE TITLE
Forcast Daten für den 3. & 4. Tag werden nicht geladen.

### ISSUE THREAD

**Issue by creecool** [ioBroker/ioBroker.openweathermap#55]
**Describe the bug**  

Es werden nur noch die Daten für heute und morgern heruntergeladen.
Auch nach einer Deinstalltion werden die Objecte im iob (Ordner) für openweathermap.0.forecast.day2  / day3 / day4 nicht mehr mit angelgt.

Problem besteht wohl schon bereits seit mehren Wochen, machte sich bemerkebar da sich das Datatum für Day 3 & 4 sich in meiner GUI nicht mehr verändert hat. 

Rufe ich mit meinem API Key die folegende Beispiel URL auf, dann erhalte ich wie gewünshct auch die Daten für Day3 & 4 
ber http://api.openweathermap.org/data/2.5/forecast?id=524901&appid=XXXXXXXXXXX  

Plattform
    linux
Betriebssystem
    linux
Architektur
    arm
Modell
    ARMv7 Processor rev 3 (v7l)
Node.js
    v14.19.2
NPM
    6.14.17
OpenWeatherMap
    0.2.4  (und auch schon 0..2.1 getesetet -gleiches ergebnis

Mein OpenWeatherAccount "Abo"
Current weather and forecast 	
Free plan 	
Hourly forecast: unavailable
Daily forecast: unavailable
Calls per minute: 60
3 hour forecast: 5 days

**Comment by Apollon77** [comment]
Can youplease post a forecast JSON from you?

**Comment by ANierbeck** [comment]
Having the same issue here only current, day0, day1 and period0 to period15 are present. 
The json is rather lengthy around 202kb still want it added here?

**Comment by Apollon77** [comment]
Yes upload as file :-)

**Comment by ANierbeck** [comment]
[openweathermap.0.forecast.json.zip](https://github.com/ioBroker/ioBroker.openweathermap/files/8800325/openweathermap.0.forecast.json.zip)
plain json wasn't accepted, therefore needed to zip it :)

**Comment by Apollon77** [comment]
I do not need the iobroker objects, I need the data json from openweathermap :-))

So the one from

 >
Rufe ich mit meinem API Key die folegende Beispiel URL auf, dann erhalte ich wie gewünshct auch die Daten für Day3 & 4
ber http://api.openweathermap.org/data/2.5/forecast?id=524901&appid=XXXXXXXXXXX

**Comment by creecool** [comment]
https://api.openweathermap.org/data/2.5/forecast?&lat=50.33670&lon=8.75726&appid=4a807021c1b5e9958d4a60cd6d57e985

**Comment by Apollon77** [comment]
Please try GitHub version - and post Debug log please if not working

**Comment by Apollon77** [comment]
@creecool Any chance to test?

**Comment by creecool** [comment]
> Please try GitHub version - and post Debug log please if not working

Hi, sorry didn't get the info for a new comment. I will test it later @home

**Comment by creecool** [comment]
Hi, for me it is working now. Perfect - Thank you. 

![image](https://user-images.githubusercontent.com/62263121/173083380-0a69f78f-bdab-4a61-a6e4-fb94ad45981e.jpeg)
