### ISSUE TITLE
Typo bei Objektname und Rolle

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.openweathermap#8]
Hallo,
unter forecast/current/visibility ist der Name mit "Actual humidity" angegeben. Das müsste aber "Actual visibility" heißen, und unter forecast/current/sunset ist die Rolle mit "date.sunrise" angegeben, hier müsste "date.sunset" stehen.

![image](https://user-images.githubusercontent.com/35137293/49747416-b157f300-fca3-11e8-8a1b-b39f4bfd8b61.png)

Gruß Steffen

**Comment by libertyx82** [comment]
Wurde bereits korrigiert
https://github.com/ioBroker/ioBroker.openweathermap/pull/7
https://github.com/ioBroker/ioBroker.openweathermap/pull/9
